### ISSUE TITLE
Could be reduced to five-char-max

### ISSUE THREAD

**Issue by sethmlarson** [petersn/six-char-max#4]
Six characters is far too many, I can barely fit the code generated by this tool on my terminal!
I suggest moving to a five character maximum with the following technique:

```python
c=chr
a=''
i=255
b=c(
i)
a+=b

# ... And so on...

exec(
a)
```

This could be reduced to 4 but for the sake of compatibility with Python 2 I've stayed at 5. This is the obviously the best reason to upgrade to Python 3.

**Comment by christopherjenness** [comment]
Line continuations sort of break the spirit of the rule.

**Comment by UsmannK** [comment]
This could also help with #3

**Comment by sethmlarson** [comment]
We're not about spirit, we're about stone-cold rules that aren't allowed to be broken. :wink:

**Comment by szabolcsdombi** [comment]
Hopefully this will be the style guide for the next python major version.
This project is awesome.

**Comment by zbanks** [comment]
See https://github.com/zbanks/four-char-max
